### ISSUE TITLE
How to connect with Coinbase Wallet?

### ISSUE THREAD

**Issue by phucnguyen1901** [RootSoft/walletconnect-dart-sdk#101]
Hi all, I tried using this package to connect to Coinbase Wallet but it didn't work. Can this package connect to Coinbase Wallet?. Thanks.

**Comment by LiRenGuo** [comment]
I have this problem too, did you solve it?

**Comment by phucnguyen1901** [comment]
You can use coinbase_wallet_sdk package, Coinbase Wallet doesn't support WalletConnect, you can create credential to request to Coinbase Wallet app by implementing Credential class
