### ISSUE TITLE
Error: SocketException a.bridge.walletconnect.org

### ISSUE THREAD

**Issue by AnhTu6610** [RootSoft/walletconnect-dart-sdk#106]
Error: SocketException: Failed host lookup: 'a.bridge.walletconnect.org' (OS Error: nodename nor servname provided, or not known, errno = 8) Stack Trace: #0 _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:706)

**Comment by suiebay** [comment]
Did you find how to resolve this issue?

This [replay](https://github.com/WalletConnect/WalletConnectFlutterV2/issues/113#issuecomment-1609675932) says that all v1 versions of walletconnect will be turned off, to resolve this issue this package should move to v2 version of walletconnect.

**Comment by AnhTu6610** [comment]
I found no solution, my app is working fine, I don't want to have to change it.

**Comment by nqhhdev** [comment]
> I found no solution, my app is working fine, I don't want to have to change it.

Can you share it for me?

**Comment by AnhTu6610** [comment]
https://docs.walletconnect.com/2.0/flutter/installation

I see walletconnect has released walletconnect v2.
But I can't find a way to connect wallet like metamask.
Can you help me.

**Comment by nqhhdev** [comment]
> https://docs.walletconnect.com/2.0/flutter/installation
> 
> I see walletconnect has released walletconnect v2. But I can't find a way to connect wallet like metamask. Can you help me.

https://github.com/WalletConnect/WalletConnectFlutterV2/issues/113 
You can follow my ticket

**Comment by RootSoft** [comment]
WalletConnect has released an official v2 library, so the (unofficial) v1 is no longer supported.

People looking to migrate to the official WalletConnect v2, please check out the [documentation](https://docs.walletconnect.com/2.0/flutter/installation) for more information regarding integration.
