### ISSUE TITLE
Wallet connect V2 issue 

### ISSUE THREAD

**Issue by jayfinava-benzatine** [RootSoft/walletconnect-dart-sdk#107]
Currently, we are using your library walletconnect_dart.   This library had working well. But it stopped working on 28 Jun 2023 due to the wallet connect v2 policy.  

Here is the wallet connect official doc:- https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/overview   

Can you please tell me when will your team give support to this library to wallet connect v2?

**Comment by RootSoft** [comment]
WalletConnect has released an official v2 library, so the (unofficial) v1 is no longer supported.

People looking to migrate to the official WalletConnect v2, please check out the [documentation](https://docs.walletconnect.com/2.0/flutter/installation) for more information regarding integration.

**Comment by jayfinava-benzatine** [comment]
@RootSoft But with this library when you will update the wallet connect V2 version?
