### ISSUE TITLE
connector.createSession is never awaited

### ISSUE THREAD

**Issue by Pepslee** [RootSoft/walletconnect-dart-sdk#11]
I`m trying to run example, but  this code

final session = await connector.createSession(
    chainId: 4160,
    onDisplayUri: (uri) => print(uri),
  );

is never awaited.

So I can`t receive session and send it into deeplink launch.

**Comment by Pepslee** [comment]
`import 'package:flutter/material.dart';
import 'package:walletconnect_dart/walletconnect_dart.dart';
import 'package:url_launcher/url_launcher.dart';

void main() async {
  final connector = WalletConnect(
    bridge: 'https://bridge.walletconnect.org',
    clientMeta: const PeerMeta(
      name: 'WalletConnect',
      description: 'WalletConnect Developer App',
      url: 'https://walletconnect.org',
      icons: [
        'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
      ],
    ),
  );

// Subscribe to events
  connector.on('connect', (session) => print(session));
  connector.on('session_update', (payload) => print(payload));
  connector.on('disconnect', (session) => print(session));

// Create a new session
  if (!connector.connected) {
    var session = await connector.createSession(
      chainId: 4160,
      onDisplayUri: (uri) => print(uri),
    );
  }
  print('*****');
}`

**Comment by Pepslee** [comment]
```import 'package:flutter/material.dart';
import 'package:walletconnect_dart/walletconnect_dart.dart';
import 'package:url_launcher/url_launcher.dart';

void main() async {
  final connector = WalletConnect(
    bridge: 'https://bridge.walletconnect.org',
    clientMeta: const PeerMeta(
      name: 'WalletConnect',
      description: 'WalletConnect Developer App',
      url: 'https://walletconnect.org',
      icons: [
        'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
      ],
    ),
  );

// Subscribe to events
  connector.on('connect', (session) => print(session));
  connector.on('session_update', (payload) => print(payload));
  connector.on('disconnect', (session) => print(session));

// Create a new session
  if (!connector.connected) {
    var session = await connector.createSession(
      chainId: 4160,
      onDisplayUri: (uri) => print(uri),
    );
  }
  print('*****');
}```

**Comment by Pepslee** [comment]
So this print('*****'); will never be printed.

**Comment by RootSoft** [comment]
For anyone else interested: the program will continue once a session has been established, for example when the QR code was scanned containing the URI, and the session was accepted on the wallet side.

You can both await the function or use one of the event handlers to continue.
