### ISSUE TITLE
How can i call  walletconnect_dart  with web3dart  in flutter

### ISSUE THREAD

**Issue by usama1050** [RootSoft/walletconnect-dart-sdk#13]
i have a smart contract with multiple functions that allow user to pay bills in crypto currencies .i just want to known how can i call smart contract functions through web3dart without private key.I already connect wallet with walletconnect_dart how can i use them instead of private key.Is there any option in walletconnect_dart to call smart contract function?

**Comment by RootSoft** [comment]
Can you be a little more specific? What blockchain are you using?
Please check out the official documentation: https://docs.walletconnect.com/
