### ISSUE TITLE
Support configure WalletConnect version

### ISSUE THREAD

**Issue by hnvn** [RootSoft/walletconnect-dart-sdk#14]
I see in codes fix the version of WalletConnect to v1. It looks like this property cannot be configured from WalletConnector. I see this warning from WalletConnect team:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">If you are using the public bridge &quot;<a href="https://t.co/OYtFcfwECQ">https://t.co/OYtFcfwECQ</a>&quot; you need to switch to v1.5.2 immediately ⚠️<br><br>We have run out of solutions to scale v1.0 for that single bridge and we already published a fix for this for Dapps to upgrade to a version 1.5.0 or higher<br><br>Upgrade now!</p>&mdash; WalletConnect 📲 (@WalletConnect) <a href="https://twitter.com/WalletConnect/status/1421092594365472773?ref_src=twsrc%5Etfw">July 30, 2021</a></blockquote>

It is better to have configurable version of WalletConnector. Thanks

**Comment by RootSoft** [comment]
@hnvn Do you have some more information regarding this?
I'm not sure that version is related to the bridge version, a walletconnect version or a specific JS client version.
The dart sdk follows the WalletConnect v1 monorepo which also handles selecting a random bridge.

**Comment by hnvn** [comment]
Sorry, I don't have much knowledge about it, just see that current WalletConnect bridge is very slow and usually cannot connect dapp to wallet (at least in case of Metamask)

**Comment by RootSoft** [comment]
I think that's related to v1 of walletconnect. Having some problems with the Algorand network as well.
I'm hoping v2 will fix this.
