### ISSUE TITLE
how to store the session so user dont have to connect wallet again and again??

### ISSUE THREAD

**Issue by kashifahmad662** [RootSoft/walletconnect-dart-sdk#2]

**Comment by RootSoft** [comment]
hi @kashifahmad662 ,

Session storage is not part of the SDK.
You can easily store the session by writing it to a file, or something like [shared_preferences](https://pub.dev/packages/shared_preferences)

**Comment by 2i2i** [comment]
How to serialise a WalletConnect object into a file? I think there is no reliable dart language method to serialise any Object.

**Comment by RootSoft** [comment]
My recommendation would be to write the fields of the session object to a (secure) location, for example:
* https://pub.dev/packages/flutter_secure_storage
* https://pub.dev/packages/shared_preferences
* https://pub.dev/packages/hive

When reconnecting, just read the fields and construct a new `WalletConnectSession` object and pass it to the `WalletConnect` constructor.

**Comment by kashifahmad662** [comment]
But there is no method described in this lib to reconnect the session from stored data there is only one filed to start a new session

**Comment by kashifahmad662** [comment]
Can u please explain it how to store the and reconnect with stored data in shared preferences

**Comment by RootSoft** [comment]
You should pass a `WalletConnectSession` to the `session` argument in the `WalletConnect` constructor to restore a session. I will update the sdk next week with better support for session storage and update the documentation

**Comment by hnvn** [comment]
> Can u please explain it how to store the and reconnect with stored data in shared preferences

There's already a class named [SessionStorage](https://github.com/RootSoft/walletconnect-dart-sdk/blob/f3ad6fa2c690381d27c6e1c4b83ba596db748b2b/lib/src/session/session_storage.dart) but it is still a blank class.

**Comment by kashifahmad662** [comment]
> You should pass a `WalletConnectSession` to the `session` argument in the `WalletConnect` constructor to restore a session. I will update the sdk next week with better support for session storage and update the documentation

Wanting for next update thanx

**Comment by hnvn** [comment]
In the meantime, I already provided an implementation of SessionStorage myself:

```dart

import 'dart:convert';
import 'dart:typed_data';
import 'package:convert/convert.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

class MyWalletConnectStorage extends SessionStorage {
  final _storage = const FlutterSecureStorage();
  final _key = 'wc_session';

  WalletConnectSession? _session;

  Future<void> intialize() async {
    final value = await _storage.read(key: _key);
    if (value != null) {
      try {
        final sessionJson = jsonDecode(value);
        if (sessionJson != null) {
          _session = WalletConnectSession(
            protocol: sessionJson['protocol'],
            version: sessionJson['version'],
            connected: sessionJson['connected'],
            accounts: (sessionJson['accounts'] as List?)
                    ?.map((e) => e.toString())
                    .toList() ??
                [],
            chainId: sessionJson['chainId'],
            bridge: sessionJson['bridge'],
            key: sessionJson['key'] != null
                ? Uint8List.fromList(hex.decode(sessionJson['key']))
                : null,
            clientId: sessionJson['clientId'],
            clientMeta: sessionJson['clientMeta'] != null
                ? PeerMeta.fromJson(sessionJson['clientMeta'])
                : null,
            peerId: sessionJson['peerId'],
            peerMeta: sessionJson['peerMeta'] != null
                ? PeerMeta.fromJson(sessionJson['peerMeta'])
                : null,
            handshakeId: sessionJson['handshakeId'],
            handshakeTopic: sessionJson['handshakeTopic'],
            networkId: sessionJson['networkId'],
            rpcUrl: sessionJson['rpcUrl'],
          );
        }
      } catch (e) {
        debugPrint(e.toString());
      }
    }
  }

  @override
  WalletConnectSession? getSession() {
    return _session;
  }

  @override
  void removeSession() {
    _storage.delete(key: _key);
  }

  @override
  void store(WalletConnectSession session) {
    final sessionJson = {
      'protocol': session.protocol,
      'version': session.version,
      'connected': session.connected,
      'accounts': session.accounts,
      'chainId': session.chainId,
      'bridge': session.bridge,
      'key': session.key != null ? hex.encode(session.key!) : null,
      'clientId': session.clientId,
      'clientMeta': session.clientMeta?.toJson(),
      'peerId': session.peerId,
      'peerMeta': session.peerMeta?.toJson(),
      'handshakeId': session.handshakeId,
      'handshakeTopic': session.handshakeTopic,
      'networkId': session.networkId,
      'rpcUrl': session.rpcUrl,
    }..removeWhere((key, value) => value == null);
    _session = session;
    _storage.write(key: _key, value: jsonEncode(sessionJson));
  }
}
```

Usage:

```dart
Future<void> initialize() async {
    final storage = MyWalletConnectStorage();
    await storage.intialize();

    final session = storage.getSession();

    // Create a connector
    _connector = WalletConnect(
      bridge: 'https://bridge.walletconnect.org',
      clientId: "clientId",
      clientMeta: const PeerMeta(
        name: "name",
        description: "description",
        url: "url",
        icons: [],
      ),
      sessionStorage: storage,
      session: session,
    );

   // check existing session
   if (session.connected) {
       // connected, do something here
   } else {
       // not connected, show connect UI
   }
}
```

**Comment by RootSoft** [comment]
thanks @hnvn! I will update the sdk with your implementation this weekend.

**Comment by RootSoft** [comment]
Updated `walletconnect_dart` to v0.0.5 to add better support for SessionStorage.
Introduced a new package `walletconnect_secure_storage` to securely store wallet connect sessions using `flutter_secure_storage` (thanks @hnvn)

See: https://pub.dev/packages/walletconnect_secure_storage
