### ISSUE TITLE
Connect Wallet by DeepLinking

### ISSUE THREAD

**Issue by DedicatedDev** [RootSoft/walletconnect-dart-sdk#21]
I'm trying to connect by deep linking. 
QR code sample was really but did not find how can I implement deeplinking. 
Is there any idea?

**Comment by RootSoft** [comment]
I'm using the following code to sign transactions using the Algorand Wallet from a deep link.
I'm launching a URI using [url_launcher](https://pub.dev/packages/url_launcher)

```dart
  /// Launch the Algorand Wallet and requests to sign the transaction.
  Future<List<Uint8List>> signTransaction(
    List<RawTransaction> transactions, {
    int delay = 4,
  }) async {
    final session = _connector.session;
    final uri =
        '${session.protocol}:${session.handshakeTopic}@${session.version}';

    final launched = await launch(uri);
    if (!launched) {
      throw WalletConnectException(
          'Do you have the Algorand Wallet installed?');
    }

    // Wait x seconds
    await Future.delayed(Duration(seconds: delay));

    // Sign the transaction
    return await _connector
        .signTransactions(transactions.map((tx) => tx.toBytes()).toList());
  }
```

**Comment by DedicatedDev** [comment]
I have no issue with sign. current my problem is just when I try to open uri, it is opening rainbow wallet always.

**Comment by RootSoft** [comment]
Closing as discussed in the Algorand Discord channel.

**Comment by DedicatedDev** [comment]
so solved issue in iOS and recover session problem?
