### ISSUE TITLE
need help about deep linking

### ISSUE THREAD

**Issue by text4lilac** [RootSoft/walletconnect-dart-sdk#27]
awsome package,can any one tell me
how to add deep linking using this package??

**Comment by RootSoft** [comment]
We use deeplinking together with [url_launcher](https://pub.dev/packages/url_launcher).
Once you create a session with `createSession`, you can launch the uri with the `launch` method of `url_launcher`.

```dart
final session = await connector.createSession(
      chainId: 4160,
      onDisplayUri: (uri) async {
        print(uri);
        try {
          if (!await launch(uri)) {
            emit(WalletConnectNotInstalled());
            return;
          }
        } catch (ex) {
          emit(WalletConnectFailure(code: 1, message: ''));
        }
      },
    );
    ```

**Comment by ekasetiawans** [comment]
on iOS you can use universal link of wallet and make sure you call launch like this:
```
 launch(
        deepLink,
        universalLinksOnly: true,
        forceSafariVC: false,
      );
```

**Comment by text4lilac** [comment]
thank you.working properly

> We use deeplinking together with [url_launcher](https://pub.dev/packages/url_launcher). Once you create a session with `createSession`, you can launch the uri with the `launch` method of `url_launcher`.
> 
> ```dart
> final session = await connector.createSession(
>       chainId: 4160,
>       onDisplayUri: (uri) async {
>         print(uri);
>         try {
>           if (!await launch(uri)) {
>             emit(WalletConnectNotInstalled());
>             return;
>           }
>         } catch (ex) {
>           emit(WalletConnectFailure(code: 1, message: ''));
>         }
>       },
>     );
>     ```
> ```

thank you (working proper)
