### ISSUE TITLE
I get an Unhandled exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by phillausofia** [RootSoft/walletconnect-dart-sdk#37]
Hello! 

I tried running the wallet.dat file in example\wallet\lib\wallet.dart but I get this error:

`Unhandled exception:
type 'Null' is not a subtype of type 'Map<String, dynamic>'
#0      WalletConnectSession.approve (package:walletconnect_dart/src/session/wallet_connect_session.dart:81:35)
#1      WalletConnect._handleSessionResponse (package:walletconnect_dart/src/walletconnect.dart:558:15)
#2      WalletConnect.createSession (package:walletconnect_dart/src/walletconnect.dart:207:11)
<asynchronous suspension>
#3      main (/StudioProjects/walletconnect-dart-sdk/example/wallet/lib/wallet.dart:6:21)
`

Using the 0.0.9 version

**Comment by RootSoft** [comment]
@phillausofia What blockchain are you using?
