### ISSUE TITLE
Unable to connect wallet in android release mode 

### ISSUE THREAD

**Issue by McDreamy** [RootSoft/walletconnect-dart-sdk#40]
I tried to connect MetaMask wallet in debug mode and is working fine. But when we create release build it stops working. It still able to open MetaMask, but after unlock the MetaMask account it won't prompt the dialog for connect wallet.

**Comment by zzyakenzz** [comment]
I had the same issue, please tell me if you have answer. Thanks!

**Comment by supafoundation** [comment]
same issue

**Comment by supafoundation** [comment]
Fixed for me following these steps: https://stackoverflow.com/questions/67978223/flutter-http-get-request-doesnt-work-on-apk-release
Trust wallet still doesnt work however

**Comment by zzyakenzz** [comment]
I fixed this issue by adding Internet permission at Manifest in android module:

 <uses-permission android:name="android.permission.INTERNET" />
 
 It's working well for me on release mode

**Comment by iamdipanshusingh** [comment]
@McDreamy can you plz let me know how did you manage to implement it? I'm not able to connect it to metamask

cc: @RootSoft
