### ISSUE TITLE
error when call sendTransaction for erc20 approve function

### ISSUE THREAD

**Issue by hamberluo** [RootSoft/walletconnect-dart-sdk#41]
JSON-RPC error -32000: execution reverted: NO_CONTRACT_FOR_FUNCTION

**Comment by Yaman-kumar** [comment]
@hamberluo Any update on this issue were you able to solve this?

**Comment by hamberluo** [comment]
yes i have solved it
i use wrong param before

**Comment by hamberluo** [comment]
> @hamberluo Any update on this issue were you able to solve this?

yes i have solved it
i use wrong param before

**Comment by LongTien15** [comment]
can you show me your approve code? I'm stuck
