### ISSUE TITLE
Invalid HMAC Exception

### ISSUE THREAD

**Issue by jaca420** [RootSoft/walletconnect-dart-sdk#46]
Any idea why this is happening? I am testing on an Android device connected via USB. Trying to connect to MetaMask. Have the example from the plugin website https://pub.dev/packages/walletconnect_dart

All I need is to connect to MM and get the wallet address.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.938, on macOS 12.3.1 21E258 darwin-x64, locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

`D/[secipm](20285): mSecIpmManager setProfileLength com.example.gtok profile:3237
E/flutter (20285): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: JSON-RPC error 0: Invalid HMAC
E/flutter (20285): #0      WalletConnectCipher.decrypt
package:walletconnect_dart/…/crypto/wallet_connect_cipher.dart:53
E/flutter (20285): <asynchronous suspension>
E/flutter (20285): #1      WalletConnect._handleIncomingMessages
package:walletconnect_dart/src/walletconnect.dart:402
E/flutter (20285): <asynchronous suspension>`

Walletutils.dart

`    if (!await canLaunchUrl(Uri.parse(uri))) {
      print(Uri.parse(uri));
      await launchUrl(Uri.parse(uri));
    } else {
      throw 'Could not open the uri.';
    }`

Sign in page:
`    // Create a connector
    final connector = WalletConnect(
      bridge: 'https://bridge.walletconnect.org',
      clientMeta: const PeerMeta(
        name: 'WalletConnect',
        description: 'WalletConnect Developer App',
        url: 'https://walletconnect.org',
        icons: [
          'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
        ],
      ),
    );`

    `// Subscribe to events
    connector.on('connect', (session) => print("session - >$session"));
    connector.on('connect', (session) => {});
    connector.on('session_update', (payload) {});
    connector.on('disconnect', (session) => print("session 2 -> $session"));`

`ElevatedButton(
                      style: raisedButtonStyle,
                      onPressed: () async {
                        if (!connector.connected) {
                          await connector
                              .createSession(
                                chainId: 4160,
                                onDisplayUri: (uri) =>
                                    WalletUtils.connectWallet(uri),
                              )
                              .then((session) => Navigator.push(
                                    context,
                                    MaterialPageRoute(
                                      builder: (context) => const Home(),
                                    ),
                                  ))
                              .catchError((onError) {
                            print(onError);
                          });
                        }
                      },
                      child: const Text('Connect Wallet'),
                    )`

**Comment by raj457036** [comment]
Hey, Can you please share the solution?
