### ISSUE TITLE
How to get the QR code?

### ISSUE THREAD

**Issue by 2i2i** [RootSoft/walletconnect-dart-sdk#5]
I tried a minimal example below, but that does not work by itself. Is there an example to show the QR code? Or does one have to create the QR code widget oneself?

```
Future<void> main() async {

    // Create a connector
    final connector = WalletConnect(
      bridge: 'https://bridge.walletconnect.org',
      clientMeta: PeerMeta(
        name: 'WalletConnect',
        description: 'WalletConnect Developer App',
        url: 'https://walletconnect.org',
        icons: [
          'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
        ],
      ),
    );

    // Set a default walletconnect provider
    connector.setDefaultProvider(AlgorandWCProvider(connector));

    // Check if connection is already established
    final session = await connector.createSession(
      chainId: 4160,
      onDisplayUri: (uri) => print(uri),
    );
}
```

**Comment by RootSoft** [comment]
This SDK isn't a wrapper around the web provider but rather a port of the existing monorepo v1.
It does not contain the QR code modal, however you can easily generate the QR using [qr_flutter](https://pub.dev/packages/qr_flutter).

All you have to do is provide the `uri` in `onDisplayUri` to the `data` field of the `QrImage`:

```
QrImage(
  data: uri,
  version: QrVersions.auto,
  size: 200.0,
)
```

**Comment by 1m1-github** [comment]
I see, thx.
I know the project is in a early version, but is it already functional? Meaning do the main features already work? Reliably?

**Comment by 2i2i** [comment]
I see, thx.
I know the project is in a early version, but is it already functional? Meaning do the main features already work? Reliably?

**Comment by 2i2i** [comment]
I notice you wrote that you are porting walletconnect monorepo v1. I think I saw they are soon to release v2 with significant improvements. Would it not make sense to make this a port of v2?

**Comment by RootSoft** [comment]
> I know the project is in a early version, but is it already functional? Meaning do the main features already work? Reliably? 

It is functional for the Algorand blockchain. I haven't had the time to support Ethereum by default.
The only thing missing at the moment is storing the session. I wasn't sure to make it part of the core SDK.

> I notice you wrote that you are porting walletconnect monorepo v1. I think I saw they are soon to release v2 with significant improvements. Would it not make sense to make this a port of v2?

The native Algorand Wallet supports only V1 for now and will be backwards-compatible (hopefully).
While I was developing this, V2 was still in beta and didn't have a lot of documentation.
Once Algorand Wallet upgrades to WC v2, I will probably update the dart sdk to V2 as well
