### ISSUE TITLE
Metamask - Accounts List Length Always 1

### ISSUE THREAD

**Issue by u382514** [RootSoft/walletconnect-dart-sdk#51]
Trying to get a list of accounts when connecting to Metamask. The list always returns the current account that is selected in Metamask, however not all of the accounts. Is this just a Metamask thing or am I missing something? We're implementing a sign-on feature using wallet connect where we would like them to select the account they want to use as their sign on, and on subsequent sign-on's, allow them to see their 'last sign on address'.

**Comment by RootSoft** [comment]
This should be a MM issue. Can you try with another wallet and see if it's the same results?

**Comment by u382514** [comment]
Well, that would be my next question. I have Pera, Trust and Metamask installed on the phone (IOS). I use URL Launcher in the onDisplayUri function. It always defaults to opening Metamask. How does one open up a different wallet using this method?

**Comment by u382514** [comment]
Forget about that last question. I just needed extra time to understand how all of this works. I have been able to connect to other wallets however it seems to still only bring over the 'current' selected account rather than a full list. At this stage though I need to do more due diligence and connect to a variety of wallets before considering this an issue. Thanks!

**Comment by RootSoft** [comment]
@u382514 this might be what your after. https://pub.dev/packages/walletconnect_qrcode_modal_dart.

Note that in the case of Pera (not sure about MM), some wallets lets you only 'select' one account, and that account gets returned in the array. Other wallets might return the entire list of addresses. It depends on the implementation on the wallet.
