### ISSUE TITLE
Not able to connect Trust wallet

### ISSUE THREAD

**Issue by VivekMakwana24** [RootSoft/walletconnect-dart-sdk#57]
Hello,

I want to connect to Trust wallet, But unfortunately it doesn't connect with it.

I have run the Mobile example app of this demo and tried to scan the QR code from the Trust Wallet, but it gives a prompt msg of **"Connecting! please wait"**  , Nothing happens after that.

**Comment by mrtnetwork** [comment]
For me, this happens when I try to connect to TrustWallet without a VPN because my country is embargoed, Or I try to make a new connection again without waiting for the connection to be established

**Comment by mahdibagjani** [comment]
I have the same problem with TrustWallet and SafePal

**Comment by mahdibagjani** [comment]
I found problem. TrustWallet and SafePal ,... (except MetaMask) just connect to mainNet. you have to change chainID from 3 (ropsten) to 1 (mainnet). That's it.

**Comment by ronpetit** [comment]
> @MohsenHaydari found problem. TrustWallet and SafePal ,... (except MetaMask) just connect to mainNet. you have to change chainID from 3 (ropsten) to 1 (mainnet). Then change Web3Client url to a mainNet url for example 'https://rpc.flashbots.net/'. That's it.
> 
> //chainID list https://besu.hyperledger.org/en/stable/Concepts/NetworkID-And-ChainID/
> 
> //mainNet urls https://chainlist.org/chain/1
> 
> //ethereum_transaction_tester.dart
> 
> ```
> final ethereum = Web3Client('https://rpc.flashbots.net/', Client());
> return connector.connect(chainId: 1, onDisplayUri: onDisplayUri);
> ```

Just to make it more clear, trust wallet won't accept any testnet, was trying over Polygon mumbai, and It didn't worked until I changed to polygon mainnet
