### ISSUE TITLE
Disconnect with a specific site 

### ISSUE THREAD

**Issue by bakrysaeed** [RootSoft/walletconnect-dart-sdk#59]
Now I'm already connected by 5 sites in different networks but when choose any site to disconnect its choose random one to disconnect not my chooseen 
![IMG-20220712-WA0023](https://user-images.githubusercontent.com/58775638/178375549-50e23a6a-dee7-49c3-a932-bffd809b5e48.jpg)

**Comment by RootSoft** [comment]
Can you make a reproducable example?
This doesn't happen on my side.
You should only call `killSession`.
Are you using the `sessionStorage`? 
Do you have multiple instances of a `WalletConnect`, or are you reusing the same instance?

Please provide some more information with your issue.

**Comment by momagdy194** [comment]
@RootSoft  can you provide example for connect to site with wallet connect 
because the original example dose not work perfectly  
i use qr scaner to scan the qr from website like https://www.pinksale.finance/  
and it sould connect to website after scan it
