### ISSUE TITLE
Support for other wallets

### ISSUE THREAD

**Issue by Rimantovas** [RootSoft/walletconnect-dart-sdk#6]
Are there any plans for support of other wallets such as metamask and crypto.com

**Comment by RootSoft** [comment]
I've received a couple of requests. I will add support for Ethereum next week.

**Comment by Rimantovas** [comment]
Glad to hear that.

**Comment by Rimantovas** [comment]
Hi, me again. Wanted to ask if the coming update will also support binance smart-chain network?

**Comment by RootSoft** [comment]
@Rimantovas I haven't worked with BSC before, but you can use the same implementation like the `AlgorandWCProvider` which also uses the `sendCustomRequest` method .

> Typically sendTransaction is used with Ethereum transaction parameters in WalletConnect dApp integrations. But in Binance Chain's case, instead of invoking sendTransaction in the WalletConnect flow, the new sendCustomRequest call is used instead with a method called bnb_sign (see below).

https://docs.binance.org/walletconnect.html

**Comment by Rimantovas** [comment]
Oh, got it. Thanks for the response. Also, are you planning to migrate the plugin to walletconnect v2 with api keys?

**Comment by RootSoft** [comment]
Yup, the goal is to update the sdk to v2 once the official native Algorand wallet supports v2. (I'm mostly working on Algorand dApps)

**Comment by Rimantovas** [comment]
Got it

**Comment by nhtlquan** [comment]
+1 for another wallets: Metamask, Trust,....
And I want using tracsaction with smart contract.
Thank

**Comment by usama1050** [comment]
@nhtlquan  did you manage to call transaction with smart contract?

**Comment by RootSoft** [comment]
See https://github.com/RootSoft/walletconnect-dart-sdk/pull/18 regarding support for other blockchains.
Feel free to give any input about the implementation.
