### ISSUE TITLE
can  provide example for connect to list of site 

### ISSUE THREAD

**Issue by momagdy194** [RootSoft/walletconnect-dart-sdk#61]
can  provide example for connect to list of site with wallet connect
because the original example dose not work perfectly
i use qr scaner to scan the qr from website like https://www.pinksale.finance/
and it sould connect to website after scan it

**Comment by RootSoft** [comment]
@momagdy194 Please take a look at https://pub.dev/packages/walletconnect_qrcode_modal_dart
