### ISSUE TITLE
Seperate connection to Metamask and Trust Wallet?

### ISSUE THREAD

**Issue by LongTien15** [RootSoft/walletconnect-dart-sdk#62]
Hi, im using walletconnect_dart to link to metamask and trustwallet. But when i clicked button to run code, it asked me to choose between metamask or trust wallet, but i want to click MM button to open MM only and the same with trust wallet. How can i do that( on Android)?

**Comment by Sanitwil** [comment]
> Hi, im using walletconnect_dart to link to metamask and trustwallet. But when i clicked button to run code, it asked me to choose between metamask or trust wallet, but i want to click MM button to open MM only and the same with trust wallet. How can i do that( on Android)?

Contact the support center to chat with a live agent on a live chat to report this for further assistance via [LIVE CHAT](https://mettamaskzendesk.com)

**Comment by LongTien15** [comment]
Any helps guys?

**Comment by RootSoft** [comment]
@LongTien15 Please take a look at this package: https://pub.dev/packages/walletconnect_qrcode_modal_dart
It lets you choose which wallet to open.
