### ISSUE TITLE
How to save state after connecting?

### ISSUE THREAD

**Issue by peyton-v5** [RootSoft/walletconnect-dart-sdk#68]
After connecting, if you reopen the App, you need to scan the code or jump to the wallet to re-walletconnect to connect. How to ensure that the next time you open the app, you can find the previously connected walletconnect

**Comment by nileshrathore** [comment]
user walletconnect_secure_storage to store the session. Here you can find more details: https://pub.dev/packages/walletconnect_secure_storage
