### ISSUE TITLE
how open trust wallet not metmask?

### ISSUE THREAD

**Issue by ArDapps** [RootSoft/walletconnect-dart-sdk#79]
every time open metamask, what is the parmas need to change to use trust wallet ?

**Comment by WingCH** [comment]
try this
```
connector.createSession(
        onDisplayUri: (uri) {
                final trustWalletUri = Uri.https('link.trustwallet.com', 'wc', {'uri': uri});
        }
);
```

**Comment by RootSoft** [comment]
Take a look here: [walletconnect_qr_modal](https://pub.dev/packages/walletconnect_qrcode_modal_dart)

**Comment by ShallowGreen** [comment]
> 
I just want users connect with metamask, how should I do? I don't want to show the select of all the wallet app,connect default with metamask

**Comment by ShallowGreen** [comment]
> try this
> 
> ```
> connector.createSession(
>         onDisplayUri: (uri) {
>                 final trustWalletUri = Uri.https('link.trustwallet.com', 'wc', {'uri': uri});
>         }
> );
> ```

@WingCH I just want connect with metamask, how should I do? I don't want to show the select of all the wallet app. just connect default with metamask

**Comment by WingCH** [comment]
@ShallowGreen 
You can use the Metamask universal link `metamask.app.link`, which works in the same way as Trust Wallet.

```
walletUri = Uri.https('metamask.app.link', 'wc', {'uri': uri});
```

**Comment by ArDapps** [comment]
CryptoWallet(universalLink: 'https://link.trustwallet.com/', deeplink: 'trust://');

**Comment by ArDapps** [comment]
> @ShallowGreen You can use the Metamask universal link `metamask.app.link`, which works in the same way as Trust Wallet.
> 
> ```
> walletUri = Uri.https('metamask.app.link', 'wc', {'uri': uri});
> ```

universalLink: 'https://link.trustwallet.com/', deeplink: 'trust://');
