### ISSUE TITLE
🔌  Silent WebSocket Disconnects

### ISSUE THREAD

**Issue by ghunkins** [RootSoft/walletconnect-dart-sdk#8]
### Issue

`SocketTransport` handles disconnects (`onError` or `onDone` events) silently by marking itself as not connected. When these disconnects occur, a `WalletConnectSession` appears to be `connected` but cannot send or receive messages.

### Impact

In `release` and `profile` mode, when a user puts the app into the background (i.e. to sign a message in their wallet app), the [sockets get closed](https://stackoverflow.com/questions/50538962/flutter-run-websocket-on-background). On return, the `session` can't send or receive messages despite it looking `connected`.

### Fix

Re-open the socket when `onError` and `onDone` events are fired.

I am opening a PR on this and will link it here.

**Comment by bobwith2bees** [comment]
This may viable workaround:
```
  // add to ScreenState  'with WidgetsBindingObserver '
  // https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html

  @override
  void initState() {
    // Register observer so we can see app lifecycle changes.
    WidgetsBinding.instance!.addObserver(this);
    super.initState();
  }

  /// The wallet connect client, sometimes loses the webSocket connection when the app is suspended
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    DateFormat dateFormat = DateFormat("HH:mm:ss");
    String dateString = dateFormat.format(DateTime.now());

    logger.d("$dateString AppLifecycleState: ${state.toString()}.");

    if (state == AppLifecycleState.resumed) {
      if (mounted) {
        if (walletConnect.connected && walletConnect.transport.connected == false)) {
          logger.e('$dateString  Wallet connected, but transport is down.  Attempt to recover.');
          appSettings.walletConnectService.walletConnect.transport.open();
        }
      }
    }
  }

  @override
  void dispose() {
    super.dispose();
    // Remove observer for app lifecycle changes.
    WidgetsBinding.instance!.removeObserver(this);
  }
```

**Comment by RootSoft** [comment]
The reconnection logic is now improved in v0.0.8.
We will also introduce a Flutter widget to keep the connection alive, based on @bobwith2bees code.

Thanks @bobwith2bees and @ghunkins
