### ISSUE TITLE
WalletConnect Protocol V1 Sunset Announced, V2 Support Plans?

### ISSUE THREAD

**Issue by bobwith2bees** [RootSoft/walletconnect-dart-sdk#82]
The WalletConnect protocol team is encouraging integrations to migrate to the V2 version of the protocol.  See the links below

* https://twitter.com/WalletConnect/status/1585297191165652993?s=20&t=QnnQ2odHKzqi2dBcmlsIkA
* https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e

Opening this issue to track / discuss plans for the walletconnect-dart-sdk supporting the V2 version of the protocol.

**Comment by RootSoft** [comment]
We've started an open discussion for an official v2 over [here](https://github.com/orgs/WalletConnect/discussions/1558). 

Feel free to collaborate for any given input

**Comment by makinghappen** [comment]
@RootSoft in your opinion how difficult would be to upgrade walletconnect-dart-sdk to V2?

**Comment by danielnordh** [comment]
Looking at getting started with wallet connect integration, and right now it seems better to wait for a v2 implementation perhaps. Is this package already using a federated model (so requiring swift and kotlin packages to be ready for v2) or is it straight dart so needs more custom work? I'm not sure how long it might take for a v2 to be available.

**Comment by RootSoft** [comment]
The internal team of WalletConnect is still in discussion for an official WalletConnect v2, so stay tuned!
Nothing more I can share for now. My recommended approach is still a federated model.

**Comment by bobwith2bees** [comment]
Still no news, but here is an updated WalletConnect Flutter feature request thread to watch: 
 
 https://github.com/orgs/WalletConnect/discussions/862#discussioncomment-4290619
 
 (The prior issue was closed as a duplicate.)

**Comment by suiebay** [comment]
> The internal team of WalletConnect is still in discussion for an official WalletConnect v2, so stay tuned! Nothing more I can share for now. My recommended approach is still a federated model.

Hi, I think it's time to switch to version v2, since the connection with method v1 is turned off

**Comment by RootSoft** [comment]
WalletConnect has released an official v2 library, so the (unofficial) v1 is no longer supported.

People looking to migrate to the official WalletConnect v2, please check out the [documentation](https://docs.walletconnect.com/2.0/flutter/installation) for more information regarding integration.
