### ISSUE TITLE
Session exist error prompt on Android

### ISSUE THREAD

**Issue by marqueeeeeee** [RootSoft/walletconnect-dart-sdk#87]
Hi, need some help on solving this issue:

It only occurs on Android, when connecting i'm getting session exist error even if the app are restarted both the dApp and metamask app.

![IMG_6779](https://user-images.githubusercontent.com/8085652/201529269-2c948367-bce7-42bf-b242-1cf376e70437.jpg)

**Comment by kinggongzilla** [comment]
+1, we have the same issue

**Comment by anhto611** [comment]
+1, we have the same issue

**Comment by RootSoft** [comment]
This is a MetaMask issue: https://github.com/MetaMask/metamask-mobile/issues/5230

In short: when launching an app using a deeplink / uri, the started Android activity remembers the session, so everytime you launch MetaMask again, it tries to reestablish the connection. 
You can even try this by launching Metamask through a WC uri and then navigating to the background (don't close), then opening Metamask from your background apps.
