### ISSUE TITLE
How to get estimate gas fees for transaction

### ISSUE THREAD

**Issue by Asadu43** [RootSoft/walletconnect-dart-sdk#92]
How to get estimate gas fees for transaction

**Comment by mmMrz** [comment]
i think it's should according the chain's offical document.

**Comment by Asadu43** [comment]
i have already done with web3dart package in which a method 
[](https://pub.dev/packages/web3dart)

```
 var p = await web3client.estimateGas(
          to: EthereumAddress.fromHex(contractAddress),
          sender: EthereumAddress.fromHex(_session!.accounts[0]),
          data: data,
        );
```
Something like that:
What is your suggested way?
